---
apt_packages:
  - cron
  - curl
  - git
  - htop
  - net-tools
  - nmap
  - sysstat
  - vim
  - gnupg
  - software-properties-common
  - psmisc
  - sudo
  - mosh

apt_install_packages: false
apt_update_packages: true
