---

- name: Redbrick Nomad, Consul and general management
  hosts: all
  gather_facts: true
  roles:
    #- { role: apt } # update all packages, equivalent to `apt update && apt upgrade`
    #- { role: ssh } # add users defined in roles/defaults/main.yml
    #- { role: fail2ban } # add and configure fail2ban with jail file located in `templates/fail2ban.jail`

- name: Configure Nomad
  hosts: nomad
  roles:
    - { role: configure-nomad } # install nomad, configure the client & server based on `templates/` and vars on nomad group