---

- name: Ensure required packages are installed
  become: true
  apt:
    name: "{{ item }}"
  with_items: ["software-properties-common", "gnupg"]
  when: ansible_os_family == "Debian"

- name: Add Hashicorp apt key
  become: true
  shell:
    cmd: "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
  register: result

- name: Print out result
  debug:
    msg: "{{ result.stdout }}"

- name: Add Hashicorp repository
  become: true
  shell:
    cmd: 'sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"'
  register: result

- name: Print out results
  debug:
    msg: "{{ result.stdout }}"
